# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


# Character list here: http://tvtropes.org/pmwiki/pmwiki.php/Characters/TransformersGeneration1Autobots
# Stopped at Aerialbots

# List of Seasons
# Miniseries
# Season 1
# Season 2
# The Transformers: The Movie
# Season 3
# Season 4

Character.destroy_all
Episode.destroy_all

# Character.create(name: 'Beachcomber', title: 'Geologist', affiliation: 'Autobot', image: 'http://i.imgur.com/0jAMLSb.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur vehicula sem, rutrum consectetur purus tincidunt id. Duis nec ligula facilisis augue tincidunt porta sit amet vel nulla. Curabitur blandit, arcu quis feugiat maximus, dolor sapien accumsan ante, nec auctor arcu tortor nec magna. Donec ullamcorper sit amet velit nec finibus. Nam congue quam eu tellus fringilla aliquet sed sed ipsum. Nulla et varius ipsum. Integer ligula tellus, varius quis orci ac, consequat fringilla sem. Aliquam nec tincidunt est. Aliquam tempus urna magna, quis imperdiet erat fringilla imperdiet. Vivamus nec porttitor massa. Nulla et varius ipsum. Integer ligula tellus, varius quis orci ac, consequat fringilla sem. Aliquam nec tincidunt est. Aliquam tempus urna magna, quis imperdiet erat fringilla imperdiet. Vivamus nec porttitor massa.' )
Character.create(name: 'Blaster', title: 'Communications', affiliation: 'Autobot', image: 'http://i.imgur.com/mgByEQ6.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur vehicula sem, rutrum consectetur purus tincidunt id. Duis nec ligula facilisis augue tincidunt porta sit amet vel nulla. Curabitur blandit, arcu quis feugiat maximus, dolor sapien accumsan ante, nec auctor arcu tortor nec magna. Donec ullamcorper sit amet velit nec finibus. Nam congue quam eu tellus fringilla aliquet sed sed ipsum. Nulla et varius ipsum. Integer ligula tellus, varius quis orci ac, consequat fringilla sem. Aliquam nec tincidunt est. Aliquam tempus urna magna, quis imperdiet erat fringilla imperdiet. Vivamus nec porttitor massa.' )
Character.create(name: 'Bluestreak', title: 'Gunner', affiliation: 'Autobot', image: 'http://i.imgur.com/LepVKPL.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur vehicula sem, rutrum consectetur purus tincidunt id. Duis nec ligula facilisis augue tincidunt porta sit amet vel nulla. Curabitur blandit, arcu quis feugiat maximus, dolor sapien accumsan ante, nec auctor arcu tortor nec magna. Donec ullamcorper sit amet velit nec finibus. Nam congue quam eu tellus fringilla aliquet sed sed ipsum. Nulla et varius ipsum. Integer ligula tellus, varius quis orci ac, consequat fringilla sem. Aliquam nec tincidunt est. Aliquam tempus urna magna, quis imperdiet erat fringilla imperdiet. Vivamus nec porttitor massa.' )
# Character.create(name: 'Brawn', title: 'Demolitions', affiliation: 'Autobot', image: 'http://i.imgur.com/QQIPils.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur vehicula sem, rutrum consectetur purus tincidunt id. Duis nec ligula facilisis augue tincidunt porta sit amet vel nulla. Curabitur blandit, arcu quis feugiat maximus, dolor sapien accumsan ante, nec auctor arcu tortor nec magna. Donec ullamcorper sit amet velit nec finibus. Nam congue quam eu tellus fringilla aliquet sed sed ipsum. Nulla et varius ipsum. Integer ligula tellus, varius quis orci ac, consequat fringilla sem. Aliquam nec tincidunt est. Aliquam tempus urna magna, quis imperdiet erat fringilla imperdiet. Vivamus nec porttitor massa.' )
Character.create(name: 'Bumblebee', title: 'Espionage', affiliation: 'Autobot', image: 'http://i.imgur.com/887k6Bg.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur vehicula sem, rutrum consectetur purus tincidunt id. Duis nec ligula facilisis augue tincidunt porta sit amet vel nulla. Curabitur blandit, arcu quis feugiat maximus, dolor sapien accumsan ante, nec auctor arcu tortor nec magna. Donec ullamcorper sit amet velit nec finibus. Nam congue quam eu tellus fringilla aliquet sed sed ipsum. Nulla et varius ipsum. Integer ligula tellus, varius quis orci ac, consequat fringilla sem. Aliquam nec tincidunt est. Aliquam tempus urna magna, quis imperdiet erat fringilla imperdiet. Vivamus nec porttitor massa.' )
Character.create(name: 'Cliffjumper', title: 'Warrior', affiliation: 'Autobot', image: 'http://i.imgur.com/15Pjz68.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur vehicula sem, rutrum consectetur purus tincidunt id. Duis nec ligula facilisis augue tincidunt porta sit amet vel nulla. Curabitur blandit, arcu quis feugiat maximus, dolor sapien accumsan ante, nec auctor arcu tortor nec magna. Donec ullamcorper sit amet velit nec finibus. Nam congue quam eu tellus fringilla aliquet sed sed ipsum. Nulla et varius ipsum. Integer ligula tellus, varius quis orci ac, consequat fringilla sem. Aliquam nec tincidunt est. Aliquam tempus urna magna, quis imperdiet erat fringilla imperdiet. Vivamus nec porttitor massa.' )
# Character.create(name: 'Cosmos', title: 'Reconnaissance & Communications', affiliation: 'Autobot', image: 'http://i.imgur.com/QQIPils.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur vehicula sem, rutrum consectetur purus tincidunt id. Duis nec ligula facilisis augue tincidunt porta sit amet vel nulla. Curabitur blandit, arcu quis feugiat maximus, dolor sapien accumsan ante, nec auctor arcu tortor nec magna. Donec ullamcorper sit amet velit nec finibus. Nam congue quam eu tellus fringilla aliquet sed sed ipsum. Nulla et varius ipsum. Integer ligula tellus, varius quis orci ac, consequat fringilla sem. Aliquam nec tincidunt est. Aliquam tempus urna magna, quis imperdiet erat fringilla imperdiet. Vivamus nec porttitor massa.' )
# Character.create(name: 'Gears', title: 'Transport, Reconnaissance', affiliation: 'Autobot', image: 'http://i.imgur.com/QQIPils.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur vehicula sem, rutrum consectetur purus tincidunt id. Duis nec ligula facilisis augue tincidunt porta sit amet vel nulla. Curabitur blandit, arcu quis feugiat maximus, dolor sapien accumsan ante, nec auctor arcu tortor nec magna. Donec ullamcorper sit amet velit nec finibus. Nam congue quam eu tellus fringilla aliquet sed sed ipsum. Nulla et varius ipsum. Integer ligula tellus, varius quis orci ac, consequat fringilla sem. Aliquam nec tincidunt est. Aliquam tempus urna magna, quis imperdiet erat fringilla imperdiet. Vivamus nec porttitor massa.' )
# Character.create(name: 'Grapple', title: 'Architect', affiliation: 'Autobot', image: 'http://i.imgur.com/cdLhAKX.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur vehicula sem, rutrum consectetur purus tincidunt id. Duis nec ligula facilisis augue tincidunt porta sit amet vel nulla. Curabitur blandit, arcu quis feugiat maximus, dolor sapien accumsan ante, nec auctor arcu tortor nec magna. Donec ullamcorper sit amet velit nec finibus. Nam congue quam eu tellus fringilla aliquet sed sed ipsum. Nulla et varius ipsum. Integer ligula tellus, varius quis orci ac, consequat fringilla sem. Aliquam nec tincidunt est. Aliquam tempus urna magna, quis imperdiet erat fringilla imperdiet. Vivamus nec porttitor massa.' )
# Character.create(name: 'Hoist', title: 'Maintenance', affiliation: 'Autobot', image: 'http://i.imgur.com/cdLhAKX.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur vehicula sem, rutrum consectetur purus tincidunt id. Duis nec ligula facilisis augue tincidunt porta sit amet vel nulla. Curabitur blandit, arcu quis feugiat maximus, dolor sapien accumsan ante, nec auctor arcu tortor nec magna. Donec ullamcorper sit amet velit nec finibus. Nam congue quam eu tellus fringilla aliquet sed sed ipsum. Nulla et varius ipsum. Integer ligula tellus, varius quis orci ac, consequat fringilla sem. Aliquam nec tincidunt est. Aliquam tempus urna magna, quis imperdiet erat fringilla imperdiet. Vivamus nec porttitor massa.' )
Character.create(name: 'Hot Rod', title: 'Cavalier', affiliation: 'Autobot', image: 'http://i.imgur.com/QQIPils.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur vehicula sem, rutrum consectetur purus tincidunt id. Duis nec ligula facilisis augue tincidunt porta sit amet vel nulla. Curabitur blandit, arcu quis feugiat maximus, dolor sapien accumsan ante, nec auctor arcu tortor nec magna. Donec ullamcorper sit amet velit nec finibus. Nam congue quam eu tellus fringilla aliquet sed sed ipsum. Nulla et varius ipsum. Integer ligula tellus, varius quis orci ac, consequat fringilla sem. Aliquam nec tincidunt est. Aliquam tempus urna magna, quis imperdiet erat fringilla imperdiet. Vivamus nec porttitor massa.' )
Character.create(name: 'Hound', title: 'Scout', affiliation: 'Autobot', image: 'http://i.imgur.com/8vbmg8h.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur vehicula sem, rutrum consectetur purus tincidunt id. Duis nec ligula facilisis augue tincidunt porta sit amet vel nulla. Curabitur blandit, arcu quis feugiat maximus, dolor sapien accumsan ante, nec auctor arcu tortor nec magna. Donec ullamcorper sit amet velit nec finibus. Nam congue quam eu tellus fringilla aliquet sed sed ipsum. Nulla et varius ipsum. Integer ligula tellus, varius quis orci ac, consequat fringilla sem. Aliquam nec tincidunt est. Aliquam tempus urna magna, quis imperdiet erat fringilla imperdiet. Vivamus nec porttitor massa.' )
# Character.create(name: 'Huffer', title: 'Construction Engineer', affiliation: 'Autobot', image: 'http://i.imgur.com/QQIPils.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur vehicula sem, rutrum consectetur purus tincidunt id. Duis nec ligula facilisis augue tincidunt porta sit amet vel nulla. Curabitur blandit, arcu quis feugiat maximus, dolor sapien accumsan ante, nec auctor arcu tortor nec magna. Donec ullamcorper sit amet velit nec finibus. Nam congue quam eu tellus fringilla aliquet sed sed ipsum. Nulla et varius ipsum. Integer ligula tellus, varius quis orci ac, consequat fringilla sem. Aliquam nec tincidunt est. Aliquam tempus urna magna, quis imperdiet erat fringilla imperdiet. Vivamus nec porttitor massa.' )
Character.create(name: 'Inferno', title: 'Search & Rescue', affiliation: 'Autobot', image: 'http://i.imgur.com/AQy7m5h.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur vehicula sem, rutrum consectetur purus tincidunt id. Duis nec ligula facilisis augue tincidunt porta sit amet vel nulla. Curabitur blandit, arcu quis feugiat maximus, dolor sapien accumsan ante, nec auctor arcu tortor nec magna. Donec ullamcorper sit amet velit nec finibus. Nam congue quam eu tellus fringilla aliquet sed sed ipsum. Nulla et varius ipsum. Integer ligula tellus, varius quis orci ac, consequat fringilla sem. Aliquam nec tincidunt est. Aliquam tempus urna magna, quis imperdiet erat fringilla imperdiet. Vivamus nec porttitor massa.' )
Character.create(name: 'Ironhide', title: 'Security', affiliation: 'Autobot', image: 'http://i.imgur.com/20mQ7Rj.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur vehicula sem, rutrum consectetur purus tincidunt id. Duis nec ligula facilisis augue tincidunt porta sit amet vel nulla. Curabitur blandit, arcu quis feugiat maximus, dolor sapien accumsan ante, nec auctor arcu tortor nec magna. Donec ullamcorper sit amet velit nec finibus. Nam congue quam eu tellus fringilla aliquet sed sed ipsum. Nulla et varius ipsum. Integer ligula tellus, varius quis orci ac, consequat fringilla sem. Aliquam nec tincidunt est. Aliquam tempus urna magna, quis imperdiet erat fringilla imperdiet. Vivamus nec porttitor massa.' )
Character.create(name: 'Jazz', title: 'Special Operations Agent', affiliation: 'Autobot', image: 'http://i.imgur.com/VfAlos6.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur vehicula sem, rutrum consectetur purus tincidunt id. Duis nec ligula facilisis augue tincidunt porta sit amet vel nulla. Curabitur blandit, arcu quis feugiat maximus, dolor sapien accumsan ante, nec auctor arcu tortor nec magna. Donec ullamcorper sit amet velit nec finibus. Nam congue quam eu tellus fringilla aliquet sed sed ipsum. Nulla et varius ipsum. Integer ligula tellus, varius quis orci ac, consequat fringilla sem. Aliquam nec tincidunt est. Aliquam tempus urna magna, quis imperdiet erat fringilla imperdiet. Vivamus nec porttitor massa.' )
Character.create(name: 'Jetfire', title: 'Air Guardian', affiliation: 'Autobot', image: 'http://i.imgur.com/6EF5gD9.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur vehicula sem, rutrum consectetur purus tincidunt id. Duis nec ligula facilisis augue tincidunt porta sit amet vel nulla. Curabitur blandit, arcu quis feugiat maximus, dolor sapien accumsan ante, nec auctor arcu tortor nec magna. Donec ullamcorper sit amet velit nec finibus. Nam congue quam eu tellus fringilla aliquet sed sed ipsum. Nulla et varius ipsum. Integer ligula tellus, varius quis orci ac, consequat fringilla sem. Aliquam nec tincidunt est. Aliquam tempus urna magna, quis imperdiet erat fringilla imperdiet. Vivamus nec porttitor massa.' )
Character.create(name: 'Mirage', title: 'Spy', affiliation: 'Autobot', image: 'http://i.imgur.com/4zS3rG5.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur vehicula sem, rutrum consectetur purus tincidunt id. Duis nec ligula facilisis augue tincidunt porta sit amet vel nulla. Curabitur blandit, arcu quis feugiat maximus, dolor sapien accumsan ante, nec auctor arcu tortor nec magna. Donec ullamcorper sit amet velit nec finibus. Nam congue quam eu tellus fringilla aliquet sed sed ipsum. Nulla et varius ipsum. Integer ligula tellus, varius quis orci ac, consequat fringilla sem. Aliquam nec tincidunt est. Aliquam tempus urna magna, quis imperdiet erat fringilla imperdiet. Vivamus nec porttitor massa.' )
# Character.create(name: 'Omega Supreme', title: 'Defense Base', affiliation: 'Autobot', image: 'http://i.imgur.com/cdLhAKX.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur vehicula sem, rutrum consectetur purus tincidunt id. Duis nec ligula facilisis augue tincidunt porta sit amet vel nulla. Curabitur blandit, arcu quis feugiat maximus, dolor sapien accumsan ante, nec auctor arcu tortor nec magna. Donec ullamcorper sit amet velit nec finibus. Nam congue quam eu tellus fringilla aliquet sed sed ipsum. Nulla et varius ipsum. Integer ligula tellus, varius quis orci ac, consequat fringilla sem. Aliquam nec tincidunt est. Aliquam tempus urna magna, quis imperdiet erat fringilla imperdiet. Vivamus nec porttitor massa.' )
Character.create(name: 'Optimus Prime', title: 'Leader of the Autobots', affiliation: 'Autobot', image: 'http://i.imgur.com/ruU3zYn.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur vehicula sem, rutrum consectetur purus tincidunt id. Duis nec ligula facilisis augue tincidunt porta sit amet vel nulla. Curabitur blandit, arcu quis feugiat maximus, dolor sapien accumsan ante, nec auctor arcu tortor nec magna. Donec ullamcorper sit amet velit nec finibus. Nam congue quam eu tellus fringilla aliquet sed sed ipsum. Nulla et varius ipsum. Integer ligula tellus, varius quis orci ac, consequat fringilla sem. Aliquam nec tincidunt est. Aliquam tempus urna magna, quis imperdiet erat fringilla imperdiet. Vivamus nec porttitor massa.' )
Character.create(name: 'Perceptor', title: 'Scientist', affiliation: 'Autobot', image: 'http://i.imgur.com/P55y0Vw.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur vehicula sem, rutrum consectetur purus tincidunt id. Duis nec ligula facilisis augue tincidunt porta sit amet vel nulla. Curabitur blandit, arcu quis feugiat maximus, dolor sapien accumsan ante, nec auctor arcu tortor nec magna. Donec ullamcorper sit amet velit nec finibus. Nam congue quam eu tellus fringilla aliquet sed sed ipsum. Nulla et varius ipsum. Integer ligula tellus, varius quis orci ac, consequat fringilla sem. Aliquam nec tincidunt est. Aliquam tempus urna magna, quis imperdiet erat fringilla imperdiet. Vivamus nec porttitor massa.' )
Character.create(name: 'Powerglide', title: 'Warrior', affiliation: 'Autobot', image: 'http://i.imgur.com/hUFJ2ph.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur vehicula sem, rutrum consectetur purus tincidunt id. Duis nec ligula facilisis augue tincidunt porta sit amet vel nulla. Curabitur blandit, arcu quis feugiat maximus, dolor sapien accumsan ante, nec auctor arcu tortor nec magna. Donec ullamcorper sit amet velit nec finibus. Nam congue quam eu tellus fringilla aliquet sed sed ipsum. Nulla et varius ipsum. Integer ligula tellus, varius quis orci ac, consequat fringilla sem. Aliquam nec tincidunt est. Aliquam tempus urna magna, quis imperdiet erat fringilla imperdiet. Vivamus nec porttitor massa.' )
Character.create(name: 'Prowl', title: 'Military Specialist', affiliation: 'Autobot', image: 'http://i.imgur.com/mIt54wq.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur vehicula sem, rutrum consectetur purus tincidunt id. Duis nec ligula facilisis augue tincidunt porta sit amet vel nulla. Curabitur blandit, arcu quis feugiat maximus, dolor sapien accumsan ante, nec auctor arcu tortor nec magna. Donec ullamcorper sit amet velit nec finibus. Nam congue quam eu tellus fringilla aliquet sed sed ipsum. Nulla et varius ipsum. Integer ligula tellus, varius quis orci ac, consequat fringilla sem. Aliquam nec tincidunt est. Aliquam tempus urna magna, quis imperdiet erat fringilla imperdiet. Vivamus nec porttitor massa.' )
Character.create(name: 'Ratchet', title: 'Medic', affiliation: 'Autobot', image: 'http://i.imgur.com/XMOTT4N.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur vehicula sem, rutrum consectetur purus tincidunt id. Duis nec ligula facilisis augue tincidunt porta sit amet vel nulla. Curabitur blandit, arcu quis feugiat maximus, dolor sapien accumsan ante, nec auctor arcu tortor nec magna. Donec ullamcorper sit amet velit nec finibus. Nam congue quam eu tellus fringilla aliquet sed sed ipsum. Nulla et varius ipsum. Integer ligula tellus, varius quis orci ac, consequat fringilla sem. Aliquam nec tincidunt est. Aliquam tempus urna magna, quis imperdiet erat fringilla imperdiet. Vivamus nec porttitor massa.' )
Character.create(name: 'Red Alert', title: 'Security Director', affiliation: 'Autobot', image: 'http://i.imgur.com/XOvdKSr.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur vehicula sem, rutrum consectetur purus tincidunt id. Duis nec ligula facilisis augue tincidunt porta sit amet vel nulla. Curabitur blandit, arcu quis feugiat maximus, dolor sapien accumsan ante, nec auctor arcu tortor nec magna. Donec ullamcorper sit amet velit nec finibus. Nam congue quam eu tellus fringilla aliquet sed sed ipsum. Nulla et varius ipsum. Integer ligula tellus, varius quis orci ac, consequat fringilla sem. Aliquam nec tincidunt est. Aliquam tempus urna magna, quis imperdiet erat fringilla imperdiet. Vivamus nec porttitor massa.' )
# Character.create(name: 'Roadbuster', title: 'Ground Assault Commander', affiliation: 'Autobot', image: 'http://i.imgur.com/cdLhAKX.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur vehicula sem, rutrum consectetur purus tincidunt id. Duis nec ligula facilisis augue tincidunt porta sit amet vel nulla. Curabitur blandit, arcu quis feugiat maximus, dolor sapien accumsan ante, nec auctor arcu tortor nec magna. Donec ullamcorper sit amet velit nec finibus. Nam congue quam eu tellus fringilla aliquet sed sed ipsum. Nulla et varius ipsum. Integer ligula tellus, varius quis orci ac, consequat fringilla sem. Aliquam nec tincidunt est. Aliquam tempus urna magna, quis imperdiet erat fringilla imperdiet. Vivamus nec porttitor massa.' )
# Character.create(name: 'RoadHauler', title: 'Transport, Resource Exploraiton', affiliation: 'Autobot', image: 'http://i.imgur.com/QQIPils.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur vehicula sem, rutrum consectetur purus tincidunt id. Duis nec ligula facilisis augue tincidunt porta sit amet vel nulla. Curabitur blandit, arcu quis feugiat maximus, dolor sapien accumsan ante, nec auctor arcu tortor nec magna. Donec ullamcorper sit amet velit nec finibus. Nam congue quam eu tellus fringilla aliquet sed sed ipsum. Nulla et varius ipsum. Integer ligula tellus, varius quis orci ac, consequat fringilla sem. Aliquam nec tincidunt est. Aliquam tempus urna magna, quis imperdiet erat fringilla imperdiet. Vivamus nec porttitor massa.' )
# Character.create(name: 'Seaspray', title: 'Naval Defense', affiliation: 'Autobot', image: 'http://i.imgur.com/cdLhAKX.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur vehicula sem, rutrum consectetur purus tincidunt id. Duis nec ligula facilisis augue tincidunt porta sit amet vel nulla. Curabitur blandit, arcu quis feugiat maximus, dolor sapien accumsan ante, nec auctor arcu tortor nec magna. Donec ullamcorper sit amet velit nec finibus. Nam congue quam eu tellus fringilla aliquet sed sed ipsum. Nulla et varius ipsum. Integer ligula tellus, varius quis orci ac, consequat fringilla sem. Aliquam nec tincidunt est. Aliquam tempus urna magna, quis imperdiet erat fringilla imperdiet. Vivamus nec porttitor massa.' )
Character.create(name: 'Sideswipe', title: 'Warrior', affiliation: 'Autobot', image: 'http://i.imgur.com/cdLhAKX.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur vehicula sem, rutrum consectetur purus tincidunt id. Duis nec ligula facilisis augue tincidunt porta sit amet vel nulla. Curabitur blandit, arcu quis feugiat maximus, dolor sapien accumsan ante, nec auctor arcu tortor nec magna. Donec ullamcorper sit amet velit nec finibus. Nam congue quam eu tellus fringilla aliquet sed sed ipsum. Nulla et varius ipsum. Integer ligula tellus, varius quis orci ac, consequat fringilla sem. Aliquam nec tincidunt est. Aliquam tempus urna magna, quis imperdiet erat fringilla imperdiet. Vivamus nec porttitor massa.' )
# Character.create(name: 'Skids', title: 'Theoretician', affiliation: 'Autobot', image: 'http://i.imgur.com/cdLhAKX.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur vehicula sem, rutrum consectetur purus tincidunt id. Duis nec ligula facilisis augue tincidunt porta sit amet vel nulla. Curabitur blandit, arcu quis feugiat maximus, dolor sapien accumsan ante, nec auctor arcu tortor nec magna. Donec ullamcorper sit amet velit nec finibus. Nam congue quam eu tellus fringilla aliquet sed sed ipsum. Nulla et varius ipsum. Integer ligula tellus, varius quis orci ac, consequat fringilla sem. Aliquam nec tincidunt est. Aliquam tempus urna magna, quis imperdiet erat fringilla imperdiet. Vivamus nec porttitor massa.' )
Character.create(name: 'Smokescreen', title: 'Diversionary Tactician', affiliation: 'Autobot', image: 'http://i.imgur.com/8fgReju.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur vehicula sem, rutrum consectetur purus tincidunt id. Duis nec ligula facilisis augue tincidunt porta sit amet vel nulla. Curabitur blandit, arcu quis feugiat maximus, dolor sapien accumsan ante, nec auctor arcu tortor nec magna. Donec ullamcorper sit amet velit nec finibus. Nam congue quam eu tellus fringilla aliquet sed sed ipsum. Nulla et varius ipsum. Integer ligula tellus, varius quis orci ac, consequat fringilla sem. Aliquam nec tincidunt est. Aliquam tempus urna magna, quis imperdiet erat fringilla imperdiet. Vivamus nec porttitor massa.' )
Character.create(name: 'Sunstreaker', title: 'Warrior', affiliation: 'Autobot', image: 'http://i.imgur.com/OGIB8P1.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur vehicula sem, rutrum consectetur purus tincidunt id. Duis nec ligula facilisis augue tincidunt porta sit amet vel nulla. Curabitur blandit, arcu quis feugiat maximus, dolor sapien accumsan ante, nec auctor arcu tortor nec magna. Donec ullamcorper sit amet velit nec finibus. Nam congue quam eu tellus fringilla aliquet sed sed ipsum. Nulla et varius ipsum. Integer ligula tellus, varius quis orci ac, consequat fringilla sem. Aliquam nec tincidunt est. Aliquam tempus urna magna, quis imperdiet erat fringilla imperdiet. Vivamus nec porttitor massa.' )
# Character.create(name: 'Topspin', title: 'Land & Sea Assault', affiliation: 'Autobot', image: 'http://i.imgur.com/cdLhAKX.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur vehicula sem, rutrum consectetur purus tincidunt id. Duis nec ligula facilisis augue tincidunt porta sit amet vel nulla. Curabitur blandit, arcu quis feugiat maximus, dolor sapien accumsan ante, nec auctor arcu tortor nec magna. Donec ullamcorper sit amet velit nec finibus. Nam congue quam eu tellus fringilla aliquet sed sed ipsum. Nulla et varius ipsum. Integer ligula tellus, varius quis orci ac, consequat fringilla sem. Aliquam nec tincidunt est. Aliquam tempus urna magna, quis imperdiet erat fringilla imperdiet. Vivamus nec porttitor massa.' )
# Character.create(name: 'Twin Twist', title: 'Demolitions', affiliation: 'Autobot', image: 'http://i.imgur.com/cdLhAKX.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur vehicula sem, rutrum consectetur purus tincidunt id. Duis nec ligula facilisis augue tincidunt porta sit amet vel nulla. Curabitur blandit, arcu quis feugiat maximus, dolor sapien accumsan ante, nec auctor arcu tortor nec magna. Donec ullamcorper sit amet velit nec finibus. Nam congue quam eu tellus fringilla aliquet sed sed ipsum. Nulla et varius ipsum. Integer ligula tellus, varius quis orci ac, consequat fringilla sem. Aliquam nec tincidunt est. Aliquam tempus urna magna, quis imperdiet erat fringilla imperdiet. Vivamus nec porttitor massa.' )
Character.create(name: 'Tracks', title: 'Warrior', affiliation: 'Autobot', image: 'http://i.imgur.com/wENkr1H.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur vehicula sem, rutrum consectetur purus tincidunt id. Duis nec ligula facilisis augue tincidunt porta sit amet vel nulla. Curabitur blandit, arcu quis feugiat maximus, dolor sapien accumsan ante, nec auctor arcu tortor nec magna. Donec ullamcorper sit amet velit nec finibus. Nam congue quam eu tellus fringilla aliquet sed sed ipsum. Nulla et varius ipsum. Integer ligula tellus, varius quis orci ac, consequat fringilla sem. Aliquam nec tincidunt est. Aliquam tempus urna magna, quis imperdiet erat fringilla imperdiet. Vivamus nec porttitor massa.' )
Character.create(name: 'Trailbreaker', title: 'Defensive Strategist', affiliation: 'Autobot', image: 'http://i.imgur.com/9AzmK04.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur vehicula sem, rutrum consectetur purus tincidunt id. Duis nec ligula facilisis augue tincidunt porta sit amet vel nulla. Curabitur blandit, arcu quis feugiat maximus, dolor sapien accumsan ante, nec auctor arcu tortor nec magna. Donec ullamcorper sit amet velit nec finibus. Nam congue quam eu tellus fringilla aliquet sed sed ipsum. Nulla et varius ipsum. Integer ligula tellus, varius quis orci ac, consequat fringilla sem. Aliquam nec tincidunt est. Aliquam tempus urna magna, quis imperdiet erat fringilla imperdiet. Vivamus nec porttitor massa.' )
# Character.create(name: 'Warpath', title: 'Warrior', affiliation: 'Autobot', image: 'http://i.imgur.com/wENkr1H.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur vehicula sem, rutrum consectetur purus tincidunt id. Duis nec ligula facilisis augue tincidunt porta sit amet vel nulla. Curabitur blandit, arcu quis feugiat maximus, dolor sapien accumsan ante, nec auctor arcu tortor nec magna. Donec ullamcorper sit amet velit nec finibus. Nam congue quam eu tellus fringilla aliquet sed sed ipsum. Nulla et varius ipsum. Integer ligula tellus, varius quis orci ac, consequat fringilla sem. Aliquam nec tincidunt est. Aliquam tempus urna magna, quis imperdiet erat fringilla imperdiet. Vivamus nec porttitor massa.' )
Character.create(name: 'Wheeljack', title: 'Mechanical Engineer', affiliation: 'Autobot', image: 'http://i.imgur.com/nVnnthO.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur vehicula sem, rutrum consectetur purus tincidunt id. Duis nec ligula facilisis augue tincidunt porta sit amet vel nulla. Curabitur blandit, arcu quis feugiat maximus, dolor sapien accumsan ante, nec auctor arcu tortor nec magna. Donec ullamcorper sit amet velit nec finibus. Nam congue quam eu tellus fringilla aliquet sed sed ipsum. Nulla et varius ipsum. Integer ligula tellus, varius quis orci ac, consequat fringilla sem. Aliquam nec tincidunt est. Aliquam tempus urna magna, quis imperdiet erat fringilla imperdiet. Vivamus nec porttitor massa.' )
# Character.create(name: 'Whirl', title: 'Aerial Assault', affiliation: 'Autobot', image: 'http://i.imgur.com/wENkr1H.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur vehicula sem, rutrum consectetur purus tincidunt id. Duis nec ligula facilisis augue tincidunt porta sit amet vel nulla. Curabitur blandit, arcu quis feugiat maximus, dolor sapien accumsan ante, nec auctor arcu tortor nec magna. Donec ullamcorper sit amet velit nec finibus. Nam congue quam eu tellus fringilla aliquet sed sed ipsum. Nulla et varius ipsum. Integer ligula tellus, varius quis orci ac, consequat fringilla sem. Aliquam nec tincidunt est. Aliquam tempus urna magna, quis imperdiet erat fringilla imperdiet. Vivamus nec porttitor massa.' )
# Character.create(name: 'Windcharger', title: 'Warrior', affiliation: 'Autobot', image: 'http://i.imgur.com/cdLhAKX.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur vehicula sem, rutrum consectetur purus tincidunt id. Duis nec ligula facilisis augue tincidunt porta sit amet vel nulla. Curabitur blandit, arcu quis feugiat maximus, dolor sapien accumsan ante, nec auctor arcu tortor nec magna. Donec ullamcorper sit amet velit nec finibus. Nam congue quam eu tellus fringilla aliquet sed sed ipsum. Nulla et varius ipsum. Integer ligula tellus, varius quis orci ac, consequat fringilla sem. Aliquam nec tincidunt est. Aliquam tempus urna magna, quis imperdiet erat fringilla imperdiet. Vivamus nec porttitor massa.' )

Character.create(name: 'Grimlock', title: 'Dinobot Commander', affiliation: 'Dinobot', image: 'http://i.imgur.com/j1I25yC.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur vehicula sem, rutrum consectetur purus tincidunt id. Duis nec ligula facilisis augue tincidunt porta sit amet vel nulla. Curabitur blandit, arcu quis feugiat maximus, dolor sapien accumsan ante, nec auctor arcu tortor nec magna. Donec ullamcorper sit amet velit nec finibus. Nam congue quam eu tellus fringilla aliquet sed sed ipsum. Nulla et varius ipsum. Integer ligula tellus, varius quis orci ac, consequat fringilla sem. Aliquam nec tincidunt est. Aliquam tempus urna magna, quis imperdiet erat fringilla imperdiet. Vivamus nec porttitor massa.' )
Character.create(name: 'Slag', title: 'Flamethrower', affiliation: 'Dinobot', image: 'http://i.imgur.com/V6KVfJu.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur vehicula sem, rutrum consectetur purus tincidunt id. Duis nec ligula facilisis augue tincidunt porta sit amet vel nulla. Curabitur blandit, arcu quis feugiat maximus, dolor sapien accumsan ante, nec auctor arcu tortor nec magna. Donec ullamcorper sit amet velit nec finibus. Nam congue quam eu tellus fringilla aliquet sed sed ipsum. Nulla et varius ipsum. Integer ligula tellus, varius quis orci ac, consequat fringilla sem. Aliquam nec tincidunt est. Aliquam tempus urna magna, quis imperdiet erat fringilla imperdiet. Vivamus nec porttitor massa.' )
Character.create(name: 'Sludge', title: 'Demolitions, Jungle Warrior', affiliation: 'Dinobot', image: 'http://i.imgur.com/twHGGmM.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur vehicula sem, rutrum consectetur purus tincidunt id. Duis nec ligula facilisis augue tincidunt porta sit amet vel nulla. Curabitur blandit, arcu quis feugiat maximus, dolor sapien accumsan ante, nec auctor arcu tortor nec magna. Donec ullamcorper sit amet velit nec finibus. Nam congue quam eu tellus fringilla aliquet sed sed ipsum. Nulla et varius ipsum. Integer ligula tellus, varius quis orci ac, consequat fringilla sem. Aliquam nec tincidunt est. Aliquam tempus urna magna, quis imperdiet erat fringilla imperdiet. Vivamus nec porttitor massa.' )
Character.create(name: 'Snarl', title: 'Warrior', affiliation: 'Dinobot', image: 'http://i.imgur.com/oosK0Y9.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur vehicula sem, rutrum consectetur purus tincidunt id. Duis nec ligula facilisis augue tincidunt porta sit amet vel nulla. Curabitur blandit, arcu quis feugiat maximus, dolor sapien accumsan ante, nec auctor arcu tortor nec magna. Donec ullamcorper sit amet velit nec finibus. Nam congue quam eu tellus fringilla aliquet sed sed ipsum. Nulla et varius ipsum. Integer ligula tellus, varius quis orci ac, consequat fringilla sem. Aliquam nec tincidunt est. Aliquam tempus urna magna, quis imperdiet erat fringilla imperdiet. Vivamus nec porttitor massa.' )
Character.create(name: 'Swoop', title: 'Bombadier', affiliation: 'Dinobot', image: 'http://i.imgur.com/Z6lkNXs.jpg', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur vehicula sem, rutrum consectetur purus tincidunt id. Duis nec ligula facilisis augue tincidunt porta sit amet vel nulla. Curabitur blandit, arcu quis feugiat maximus, dolor sapien accumsan ante, nec auctor arcu tortor nec magna. Donec ullamcorper sit amet velit nec finibus. Nam congue quam eu tellus fringilla aliquet sed sed ipsum. Nulla et varius ipsum. Integer ligula tellus, varius quis orci ac, consequat fringilla sem. Aliquam nec tincidunt est. Aliquam tempus urna magna, quis imperdiet erat fringilla imperdiet. Vivamus nec porttitor massa.' )

# Miniseries
Episode.create(name: 'More Than Meets the Eye, Part 1', season: 'Miniseries', episode: 1)
Episode.create(name: 'More Than Meets the Eye, Part 2', season: 'Miniseries', episode: 2)
Episode.create(name: 'More Than Meets the Eye, Part 3', season: 'Miniseries', episode: 3)

Episode.create(name: 'Transport to Oblivion', season: '1', episode: 1)
Episode.create(name: 'Roll for It', season: '1', episode: 2)
Episode.create(name: 'Divide and Conquer', season: '1', episode: 3)
Episode.create(name: 'S.O.S. Dinobots', season: '1', episode: 4)
Episode.create(name: 'The Ultimate Doom, Part 1', season: '1', episode: 5)
Episode.create(name: 'The Ultimate Doom, Part 2', season: '1', episode: 6)
Episode.create(name: 'The Ultimate Doom, Part 3', season: '1', episode: 7)
Episode.create(name: 'War of the Dinobots', season: '1', episode: 8)
Episode.create(name: 'Countdown to Extinction', season: '1', episode: 9)
Episode.create(name: 'Fire in the Sky', season: '1', episode: 10)
Episode.create(name: 'Heavy Metal War', season: '1', episode: 11)
Episode.create(name: 'Fire on the Mountain', season: '1', episode: 12)
Episode.create(name: 'A Plague of Insecticons', season: '1', episode: 13)
